Add (Emum, str) base class support
adsharma/py2many pull request #10
Opened 2021-04-10 11:30 UTC by jayvdb

2021-04-10 20:31 UTC, adsharma requested changes
Typo in the description: Emum -> Enum

2021-04-10 20:31 UTC, adsharma commented on pyrs/transpiler.py
> +        return f"#[derive(Debug, PartialEq, EnumString)]\n{self.visit_IntEnum(node)}"
Rename logic to `visit_Enum` or `visit_CommonEnum` and then have Int/StrEnum reuse the same code.
Also a test case similar to int_enum.py for code coverage in the same commit.

2021-04-12 16:30 UTC, adsharma commented
Merged thanks!

2021-04-12 16:30 UTC, closed without merging

2021-04-12 19:26 UTC, jayvdb commented
Actually you merged your own version of this, and the generated code failed to compile.