ci: Run CI on all branches
adsharma/py2many pull request #431
Opened 2021-07-14 21:15 UTC by div72

When I first started working on the V PR, I was confused on why the CI didn't run on my branch. The main only setup is unusual and not exactly optimal in my opinion. It forces people to either do work only on the main branch, make a PR to the main branch in this repo or manually run the workflows everytime.

2021-07-14 22:18 UTC, adsharma commented
There may be another reason why the CI didn't run on the V PR. It's because it was your first PR (which requires explicit approval). Subsequent PRs should automatically run CI.

2021-07-14 22:21 UTC, div72 commented
I was talking about running on the fork, not the main repo. CI does not run on the branches outside of main in this repo either.

2021-07-15 03:46 UTC, adsharma approved these changes

2021-07-20 17:07 UTC, adsharma requested changes
I thought about it a bit more. Sometimes I push to a feature branch and then create a PR.
I may not want CI to run until the code is ready, at which point I'll create a PR against main.

Looks like the current flow is working for you more or less?

2021-07-21 21:11 UTC, div72 commented
> Looks like the current flow is working for you more or less?

I am used to it, but still it's not exactly ideal in my opinion.

> Sometimes I push to a feature branch and then create a PR.
I may not want CI to run until the code is ready, at which point I'll create a PR against main.

You can develop it locally and push it only when you want to make a PR, or use `[skip ci]` to prevent a CI from running in a commit.

2021-07-21 21:33 UTC, merged